//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultidiskBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultidiskBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation complete. All files will be able to be backed up. Continue?.
        /// </summary>
        internal static string All_files_will_be_able_to_be_backed_up {
            get {
                return ResourceManager.GetString("All_files_will_be_able_to_be_backed_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup complete..
        /// </summary>
        internal static string Backup_Complete {
            get {
                return ResourceManager.GetString("Backup_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files from the last operation that have been skipped can be loaded. Press [Yes] To load these files or [No] to start a new backup.
        /// </summary>
        internal static string Can_load_files {
            get {
                return ResourceManager.GetString("Can_load_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to back up?.
        /// </summary>
        internal static string Continue_to_back_up {
            get {
                return ResourceManager.GetString("Continue_to_back_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when saving log files.
        /// </summary>
        internal static string Error_when_saving_log_files {
            get {
                return ResourceManager.GetString("Error_when_saving_log_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete file.
        /// </summary>
        internal static string Failed_to_delete_file {
            get {
                return ResourceManager.GetString("Failed_to_delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less free space is shown in the Destinations box than what is reported by the operating system because it cannot be guaranteed that a particular file can fit on a drive. If, for example, a drive is 100MB, a file that is 100MB may not be able to fit on it because of hard drive sector restrictions and space reserved by the file system. 
        ///
        ///This application calculates free space that can be safely used by multiplying the free space reported by Windows by 0.92. If this number is less than 500MB, this drive cannot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help_1 {
            get {
                return ResourceManager.GetString("Help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files saved.
        /// </summary>
        internal static string Log_files_saved {
            get {
                return ResourceManager.GetString("Log_files_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are still files from a previous operation that have not been backed up yet. You can resume this backup operation by starting this application again..
        /// </summary>
        internal static string OnClosing_Notification {
            get {
                return ResourceManager.GetString("OnClosing_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume backup?.
        /// </summary>
        internal static string Resume_backup {
            get {
                return ResourceManager.GetString("Resume_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved operation.
        /// </summary>
        internal static string Saved_operation {
            get {
                return ResourceManager.GetString("Saved_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files could not be backed up. Press [Yes] to try again.
        /// </summary>
        internal static string Some_files_could_not_be_backed_up {
            get {
                return ResourceManager.GetString("Some_files_could_not_be_backed_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files could not be backed up:.
        /// </summary>
        internal static string Some_files_could_not_be_backed_up_short {
            get {
                return ResourceManager.GetString("Some_files_could_not_be_backed_up_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again?.
        /// </summary>
        internal static string Try_again {
            get {
                return ResourceManager.GetString("Try_again", resourceCulture);
            }
        }
    }
}
